Models/Expense_limit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;


namespace Expensetracker.Models
{
    [Table("expense_limit")]
    public class Expense_limit
    {
        [Key]
        public int e_id { get; set; }
        [Required]
        public int Total_expense { get; set; }
        [Required]
        public int Total_expense_limit { get; set; }
    }
}

Controllers/ExpenselimitController.cs
using Expensetracker.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Expensetracker.Controllers
{
    public class ExpenselimitController : Controller
    {
        Expensecontext expensctx = new Expensecontext();
        // GET: Expenselimit
        public ActionResult Index()
        {
            IList<Expense_limit> expenselimitlist = expensctx.expense_limits.ToList();
            return View(expenselimitlist);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Expense_limit e)
        {
            expensctx.expense_limits.Add(e);
            int a=expensctx.SaveChanges();
            if (a > 0)
            {
                TempData["insertmsg"] = "<script>alert('Data Inserted..!!')</script>";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["insertmsg"] = "<script>alert('Data not Inserted..!!')</script>";
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            var row = expensctx.expense_limits.Where(model => model.e_id == id).FirstOrDefault();
            return View(row);
        }
        [HttpPost]
        public ActionResult Edit(Expense_limit ex)
        {
            expensctx.Entry(ex).State = EntityState.Modified;
            int a=expensctx.SaveChanges();
            if (a > 0)
            {
                TempData["updatemsg"] = "<script>alert('Data updated..!!')</script>";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["updatemsg"] = "<script>alert('Data not updated..!!')</script>";
                return View();
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            if (id > 0)
            {
                var rowdelete = expensctx.expense_limits.Where(model => model.e_id == id).FirstOrDefault();
                if (rowdelete != null)
                {
                    expensctx.Entry(rowdelete).State = EntityState.Deleted;
                    int a = expensctx.SaveChanges();
                    if (a > 0)
                    {
                        TempData["Del"] = "<script>alert('Data Deleted..!!')</script>";
                    }
                    else
                    {
                        TempData["Del"] = "<script>alert('Data not Deleted..!!')</script>";
                    }
                }
            }
            return RedirectToAction("Index");
        }

    }
}

Views/Expenselimit/Create.cshtml
@model Expensetracker.Models.Expense_limit
<link href="~/Content/StyleSheet3buttons.css" rel="stylesheet" />
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Raw(TempData["insertmsg"])
<h2 class="heading">Create Expense Limit</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    

    <div class="form-group">
        @Html.LabelFor(model => model.Total_expense, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Total_expense, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Total_expense, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Total_expense_limit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Total_expense_limit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Total_expense_limit, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" id="savebutton"/>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Expenselimit/Edit.cshtml
@model Expensetracker.Models.Expense_limit
<link href="~/Content/StyleSheet3buttons.css" rel="stylesheet" />
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Raw(TempData["updatemsg"])
<h2 class="heading">Edit Expense Limit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.e_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Total_expense, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total_expense, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total_expense, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total_expense_limit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total_expense_limit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total_expense_limit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" id="savebutton"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Expenselimit/Index.cshtml
@model IEnumerable<Expensetracker.Models.Expense_limit>
<link href="~/Content/StyleSheet3buttons.css" rel="stylesheet" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Raw(TempData["insertmsg"])
@Html.Raw(TempData["updatemsg"])
<h2 class="heading">Expense Limit</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Total_expense)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total_expense_limit)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        using (Html.BeginForm("Delete", "Expenselimit", new { Id = item.e_id }))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Total_expense)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total_expense_limit)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.e_id }) |
                    @*@Html.ActionLink("Details", "Details", new { id = item.e_id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.e_id })*@
                    <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete the record with id=@item.e_id');"
                           style="background-color:red; color:white; font-size:16px; border:none; border-radius:8px; width:80px;"/>

                </td>
            </tr>
        }
    }

</table>
@foreach (var i in Model)
{
    if(i.Total_expense > i.Total_expense_limit)
    {
        <h3><script>alert('total expense is greater then total limit, Please...edit your data.')</script></h3>
    }

}